### ISSUE TITLE
Issue on apply

### ISSUE THREAD

**Issue by vialde** [cloudfoundry-community/terraform-provider-cloudfoundry#404]
Hello,

I'm getting the following error when trying to apply....any ideas?  Go isn't my thing

`Stack trace from the terraform-provider-cloudfoundry_v0.15.3 plugin:

panic: Put "https://api.xxx.xxx/v2/apps/445d0a4b-eebc-4796-ba9d-0f092ad7347b/bits": net/http: HTTP/1.x transport connection broken: http: ContentLength=419 with Body length 72401

goroutine 60 [running]:
github.com/terraform-providers/terraform-provider-cloudfoundry/cloudfoundry/managers/bits.BitsManager.UploadApp({0xc0002b0540?, 0xc00019cc80?, 0xc000536c80?, 0xc000469c20?}, {0xc00028a600, 0x24}, {0xc000046540?, 0x0?})
        github.com/terraform-providers/terraform-provider-cloudfoundry/cloudfoundry/managers/bits/bitsmanager.go:241 +0x885
github.com/terraform-providers/terraform-provider-cloudfoundry/cloudfoundry/managers/appdeployers.Standard.Deploy.func5(0x0?)
        github.com/terraform-providers/terraform-provider-cloudfoundry/cloudfoundry/managers/appdeployers/standard_strategy.go:103 +0x14f
github.com/terraform-providers/terraform-provider-cloudfoundry/cloudfoundry/managers/appdeployers.Actions.Execute({0xc0001fb008, 0x5, 0x0?})
        github.com/terraform-providers/terraform-provider-cloudfoundry/cloudfoundry/managers/appdeployers/rewind.go:219 +0x7e
github.com/terraform-providers/terraform-provider-cloudfoundry/cloudfoundry/managers/appdeployers.Standard.Deploy({_, _, _}, {{{0x0, {0x0, 0x0}}, {0x0, {0x0, 0x0}}, {0x0, ...}, ...}, ...})
        github.com/terraform-providers/terraform-provider-cloudfoundry/cloudfoundry/managers/appdeployers/standard_strategy.go:137 +0x350
github.com/terraform-providers/terraform-provider-cloudfoundry/cloudfoundry/managers/appdeployers.BlueGreenV2.Deploy({_, _, _, _, _}, {{{0x0, {0x0, 0x0}}, {0x0, {0x0, ...}}, ...}, ...})
        github.com/terraform-providers/terraform-provider-cloudfoundry/cloudfoundry/managers/appdeployers/bluegreenv2_strategy.go:50 +0x158
github.com/terraform-providers/terraform-provider-cloudfoundry/cloudfoundry.resourceAppCreate({0x1cfd9e8?, 0xc0003d07b0?}, 0x1a43800?, {0x1aba9a0?, 0xc00053ca00})
        github.com/terraform-providers/terraform-provider-cloudfoundry/cloudfoundry/resource_cf_app.go:290 +0x29d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0004410a0, {0x1cfd9e8, 0xc0003d07b0}, 0xd?, {0x1aba9a0, 0xc00053ca00})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/resource.go:342 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0004410a0, {0x1cfd9e8, 0xc0003d07b0}, 0xc0004a4a90, 0xc000721b80, {0x1aba9a0, 0xc00053ca00})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/resource.go:472 +0x83a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000295c38, {0x1cfd940?, 0xc000536f00?}, 0xc00007d0e0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.12.0/helper/schema/grpc_provider.go:1021 +0xdaa
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0004123c0, {0x1cfd9e8?, 0xc00019f560?}, 0xc0005c60e0)
        github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/tf5server/server.go:812 +0x515
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x1b411c0?, 0xc0004123c0}, {0x1cfd9e8, 0xc00019f560}, 0xc0004d06c0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.8.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002aee00, {0x1d01568, 0xc00044eb60}, 0xc00012ec60, 0xc000421e30, 0x2357960, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0002aee00, {0x1d01568, 0xc00044eb60}, 0xc00012ec60, 0x0)
        google.golang.org/grpc@v1.45.0/server.go:1619 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.45.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.45.0/server.go:919 +0x28a

Error: The terraform-provider-cloudfoundry_v0.15.3 plugin crashed!
`

**Comment by vialde** [comment]
The app is being created in cloundfoundry though, just nothing after that.
